config/routes.rb
DjMeetsDentex::Application.routes.draw do

  resources :fish
end

app/models/fish.rb
class Fish < ActiveRecord::Base
  attr_accessible :is_tasty, :length, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
  # GET /fish
  # GET /fish.json
  def index
    @fish = Fish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fish }
    end
  end

  # GET /fish/1
  # GET /fish/1.json
  def show
    @fish = Fish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fish }
    end
  end

  # GET /fish/new
  # GET /fish/new.json
  def new
    @fish = Fish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fish }
    end
  end

  # GET /fish/1/edit
  def edit
    @fish = Fish.find(params[:id])
  end

  # POST /fish
  # POST /fish.json
  def create
    @fish = Fish.new(params[:fish])

    respond_to do |format|
      if @fish.save
        format.html { redirect_to @fish, notice: 'Fish was successfully created.' }
        format.json { render json: @fish, status: :created, location: @fish }
      else
        format.html { render action: "new" }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fish/1
  # PUT /fish/1.json
  def update
    @fish = Fish.find(params[:id])

    respond_to do |format|
      if @fish.update_attributes(params[:fish])
        format.html { redirect_to @fish, notice: 'Fish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fish/1
  # DELETE /fish/1.json
  def destroy
    @fish = Fish.find(params[:id])
    @fish.destroy

    respond_to do |format|
      format.html { redirect_to fish_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fish_helper.rb
module FishHelper
end

app/views/fish/_form.html.erb
<%= form_for(@fish) do |f| %>
  <% if @fish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fish.errors.count, "error") %> prohibited this fish from being saved:</h2>

      <ul>
      <% @fish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :is_tasty %><br />
    <%= f.check_box :is_tasty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fish/edit.html.erb
<h1>Editing fish</h1>

<%= render 'form' %>

<%= link_to 'Show', @fish %> |
<%= link_to 'Back', fish_index_path %>

app/views/fish/index.html.erb
<h1>Listing fish</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Length</th>
    <th>Is tasty</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fish.each do |fish| %>
  <tr>
    <td><%= fish.name %></td>
    <td><%= fish.length %></td>
    <td><%= fish.is_tasty %></td>
    <td><%= link_to 'Show', fish %></td>
    <td><%= link_to 'Edit', edit_fish_path(fish) %></td>
    <td><%= link_to 'Destroy', fish, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fish', new_fish_path %>

app/views/fish/new.html.erb
<h1>New fish</h1>

<%= render 'form' %>

<%= link_to 'Back', fish_index_path %>

app/views/fish/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @fish.name %>
</p>

<p>
  <b>Length:</b>
  <%= @fish.length %>
</p>

<p>
  <b>Is tasty:</b>
  <%= @fish.is_tasty %>
</p>


<%= link_to 'Edit', edit_fish_path(@fish) %> |
<%= link_to 'Back', fish_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DjMeetsDentex</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>